### ISSUE TITLE
Consume GraphQL materials

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/nodejs-playground#11]
# [GraphQL Crash Course](https://www.youtube.com/playlist?list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y)

## Done 

- [x] [GraphQL Crash Course #1 - What is GraphQL?](https://www.youtube.com/watch?v=xMCnDesBggM&list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y)
- [x] [GraphQL Crash Course #2 - Query Basics](https://www.youtube.com/watch?v=39CPVkZE4nM&list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y&index=2)
- [x] [GraphQL Crash Course #3 - Making a GraphQL Server (with Apollo)](https://www.youtube.com/watch?v=q6MxsS2iPnw&list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y&index=4)
- [x] [GraphQL Crash Course #4 - Schema & Types](https://www.youtube.com/watch?v=ginCmJEdZ0g&list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y&index=4)
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] [GraphQL Crash Course #9 - Update Mutation](https://www.youtube.com/watch?v=2wWNslOgfhU&list=PL4cUxeGkcC9gUxtblNUahcsg0WLxmrK_y&index=10)

**Comment by xuyuji9000** [comment]
Closing this issue to focus on #10

**Comment by xuyuji9000** [comment]
Closing this issue to focus on #12

**Comment by xuyuji9000** [comment]
All video watched.

Closing this issue.
